### ISSUE TITLE
Can't export

### ISSUE THREAD

**Issue by melsbacksfriend** [Reisyukaku/GFBMDL_Plugin#5]
I'm trying to export a model and I'm getting the error below.  What can I do to fix this?  

Traceback (most recent call last):
  File "C:\Users\pkmnf\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_gfbmdl\__init__.py", line 75, in execute
    return ExportModel.save( self, context )
  File "C:\Users\pkmnf\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_gfbmdl\export_model.py", line 902, in save
    bin, off = get_model_string( context )
  File "C:\Users\pkmnf\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_gfbmdl\export_model.py", line 869, in get_model_string
    group = CreateGroups(builder)
  File "C:\Users\pkmnf\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_gfbmdl\export_model.py", line 824, in CreateGroups
    groups.append(CreateGroup(builder, 0, g, meshBounds[g]))
IndexError: list index out of range

location: <unknown location>:-1

**Comment by Reisyukaku** [comment]
Its heavily work in progress, but it looks like its not finding meshes to get bounds off of.

**Comment by melsbacksfriend** [comment]
Thanks for the help.
